export const APP_LOAD = 'APP_LOAD';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const RESTAURANT_LOAD = 'RESTAURANT_LOAD';
export const RESTAURANT_UNLOAD = 'RESTAURANT_UNLOAD';
export const RESTAURANT_SELECTED = 'RESTAURANT_SELECTED';