export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const RESTAURANTS_LOAD = 'RESTAURANTS_LOAD';
export const RESTAURANTS_UNLOAD = 'RESTAURANTS_UNLOAD';
export const RESTAURANT_SELECTED = 'RESTAURANT_SELECTED';
export const RESTAURANT_CHANGED = 'RESTAURANT_CHANGED';
export const RESTAURANT_UPDATE = 'RESTAURANT_UPDATE';